
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios; // Use the iOS options
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNWyAlXcAaa3_ODwFVtmPJbCeH13aoJCU',
    appId: '1:125390613754:web:73e121e998d02123df6d43',
    messagingSenderId: '125390613754',
    projectId: 'easyfarm-31bcd',
    authDomain: 'easyfarm-31bcd.firebaseapp.com',
    storageBucket: 'easyfarm-31bcd.firebasestorage.app',
    measurementId: 'G-4H8FVMRMEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqQFLyiVPzqn8XlTjpHj2HK54u6oz7Dh0',
    appId: '1:125390613754:android:8a9c37ef3116ee9fdf6d43',
    messagingSenderId: '125390613754',
    projectId: 'easyfarm-31bcd',
    storageBucket: 'easyfarm-31bcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // REPLACE WITH YOUR VALUE
    appId: 'YOUR_IOS_APP_ID', // REPLACE WITH YOUR VALUE
    messagingSenderId: '125390613754',
    projectId: 'easyfarm-31bcd',
    storageBucket: 'easyfarm-31bcd.firebasestorage.app',
    iosBundleId: 'com.example.myapp', // REPLACE WITH YOUR iOS Bundle ID
  );
}
